version: '3.9'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - MYSQL_DATABASE=files
      - MYSQL_USER=scor32k
      - MYSQL_PASSWORD=abhishek
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud_data:/var/www/html

  db:
    image: mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=files
      - MYSQL_USER=scor32k
      - MYSQL_PASSWORD=abhishek
      - MYSQL_ROOT_PASSWORD=abhishek
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped

volumes:
  db_data: {}
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/nextcloud
      o: bind